### ISSUE TITLE
Bitbucket Server 2.11+ and YACC (1.11) incompatibility.

### ISSUE THREAD

**Issue by mgillespie** [sford/yet-another-commit-checker#137]
https://jira.atlassian.com/browse/BSERV-9388?focusedCommentId=1011027&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1011027

**Comment by mgillespie** [comment]
Callstack

> com.isroot.stash.plugin.YaccHook failed.
java.lang.RuntimeException: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 81a8ddad8988952860fedf18616aabcabdf08ee3
	at com.isroot.stash.plugin.CommitsServiceImpl.getNewCommits(CommitsServiceImpl.java:118) ~[na:na]
	at com.isroot.stash.plugin.YaccServiceImpl.checkRefChange(YaccServiceImpl.java:53) ~[na:na]
	at com.isroot.stash.plugin.YaccHook.onReceive(YaccHook.java:70) ~[na:na]
	at com.atlassian.stash.internal.hook.repository.PreReceiveRepositoryHookAdapter$1.visit(PreReceiveRepositoryHookAdapter.java:38) [bitbucket-service-impl-4.13.0.jar:na]
	at com.atlassian.stash.internal.hook.repository.PreReceiveRepositoryHookAdapter$1.visit(PreReceiveRepositoryHookAdapter.java:33) [bitbucket-service-impl-4.13.0.jar:na]
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService$RepositoryHookPagedTransactionCallback.doInTransaction(DefaultRepositoryHookService.java:573) [bitbucket-service-impl-4.13.0.jar:na]
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService$RepositoryHookPagedTransactionCallback.doInTransaction(DefaultRepositoryHookService.java:549) [bitbucket-service-impl-4.13.0.jar:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) [spring-tx-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.visitEnabledHooks(DefaultRepositoryHookService.java:279) [bitbucket-service-impl-4.13.0.jar:na]
	at com.atlassian.stash.internal.plugin.OsgiSafeProxyProvider$1.invoke(OsgiSafeProxyProvider.java:93) [bitbucket-platform-4.13.0.jar:na]
	at com.atlassian.stash.internal.hook.repository.PreReceiveRepositoryHookAdapter.onReceive(PreReceiveRepositoryHookAdapter.java:33) [bitbucket-service-impl-4.13.0.jar:na]
	at com.atlassian.stash.internal.hook.DefaultBuiltInHookHandlerFactory$1.handle(DefaultBuiltInHookHandlerFactory.java:44) [bitbucket-service-impl-4.13.0.jar:na]
	at com.atlassian.stash.internal.scm.git.GitQuarantineHelper.lambda$null$0(GitQuarantineHelper.java:87) [bitbucket-git-4.13.0.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.doHandleRequest(DefaultHookService.java:303) ~[bitbucket-service-impl-4.13.0.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.handleRequest(DefaultHookService.java:289) ~[bitbucket-service-impl-4.13.0.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.handleRawRequest(DefaultHookService.java:230) ~[bitbucket-service-impl-4.13.0.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService$1.lambda$run$0(DefaultHookService.java:197) ~[bitbucket-service-impl-4.13.0.jar:na]
	at com.atlassian.stash.internal.concurrent.StateTransferringExecutor$StateTransferringRunnable.run(StateTransferringExecutor.java:70) ~[bitbucket-platform-4.13.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]

>

**Comment by mgillespie** [comment]
Before someone asks, didn't update to 2.12, as it doesn't specifically mention fixing this issue, and don't want to compound problems with new features that don't affect us.  (had bad experiences with "another JIRA commit checker", and all hell breaking loose in the past, so nervous of taking updates without reason).

**Comment by sford** [comment]
Hi @mgillespie , 

I am trying to understand the root issue here... are you reporting the BBS incompatibility issue with Git 2.11 (BSERV-9388), or is this is a new issue with YACC specifically after following the recommended fix for BSERV-9388?

**Comment by mgillespie** [comment]
Hi,  all was working fine,  apt upgraded git to 2.11 and it stopped accepting pushes.  Bitbucket Server says it's compatible in latest version (which we are running), but it appears YACC may not be.

**Comment by sford** [comment]
So, Git is `2.11` and BBS is at `4.13`? (just want to make sure I understand)

**Comment by mgillespie** [comment]
Yes, and YACC is 1.11

**Comment by sford** [comment]
Just adding an update ~ I can reproduce the problem and am currently working on a fix.

I removed `4.13` compatibility from the plugin in the marketplace because I suspect others will run into this when upgrading to latest BBS.

I suspect that upgrading BSS to 4.13 but using an older git will work though (as a temporary solution)

**Comment by SandyMotyl** [comment]
Sean:  I know you are early in the analysis of this, but when you are able can you clarify something for this issue?  
- For mgillespie, the problem happened when git was upgraded to 2.11
- You removed 4.13 compatibility from marketplace, although suspect that using an older git will work

I am in the process of testing a bitbucket upgrade (bbs 4.13.0 / git 2.10.0 / YACC 1.11).  I am now wondering if I should fallback to bbs 4.12.1.  We are hoping to stay on YACC 1.11 to avoid a qualification effort there and get our bitbucket upgrade to production as soon as possible.

When you have determined what combination of versions causes the problem, that information would be helpful.  FWIW: I appreciate that you were proactive with removing 4.13.0 compatibility until you knew for sure!

Thanks - Sandy

**Comment by mgillespie** [comment]
We are running bbs 4.13.0 / git 2.10.0 / YACC 1.12 successfully, so I think you should be OK..

**Comment by sford** [comment]
@SandyMotyl You should be fine with BBS 4.13.0 / git 2.10.0 / YACC 1.11 (as @mgillespie also mentioned)

Yeah... I proactively removed 4.13.0 compatibility because I figured a lot of users were hit by the git 2.11 / BBS issues and were probably eagerly waiting for the BBS 4.13.0 release. I was worried about people getting hit extra hard with running into YACC problems after upgrading to fix existing git 2.11 problems with BBS :-(

I have YACC working with git 2.11 ~ I just need to do some refactoring and testing before releasing.

**Comment by sford** [comment]
@SandyMotyl @mgillespie I just released YACC 1.13 which is compatible with git 2.11.

I added BBS 4.13 back to YACC 1.12. 

Thanks!

**Comment by SandyMotyl** [comment]
Thanks for all your quick work on sorting these issues out!  One more question:

Prior to this issue, both YACC 1.11 and 1.12 were listed as compatible with BBS 4.13.0, and you proactively removed that compatibility while looking at this problem.  As you started your investigation, you thought that my config (BBS 4.13.0 / git 2.10.0 / YACC 1.11) should be OK.

A couple of days ago, You added BBS 4.13 compatibility back to YACC 1.12, but didn't restore compatibility for YACC 1.11.  Is there really a problem with BBS 4.13.0 and YACC 1.11?  If not, could you restore that compatibility too?  We are trying to limit the items we change because we needed the bitbucket upgrade months ago (of course!).

Thanks again...

**Comment by sford** [comment]
@SandyMotyl I restored 4.13.0 compatibility to YACC 1.11. As far as I know, it should be fine, but, I haven't personally tested it. Good luck on the upgrade!
