### ISSUE TITLE
How to resolve NoSuchCommitException?

### ISSUE THREAD

**Issue by ooooo84** [sford/yet-another-commit-checker#152]
I'm an amateur of JIRA & Bitbucket server.

Here are my environment:
Windows server 2012
JIRA Software 7.2.8
Bitbucket server 4.10.2
Git 2.12.2
YACC 1.15
Sourcetree 2.0.18.1

It has NoSuchCommitException after YACC enabled for repository. Even there doesn't have any restrictions.

Here is the debug log:
`WARN  [threadpool:thread-1] admin @L8Y7JUx626x2791x0 10.206.29.193 "POST /scm/tpone/test-repository-1.git/git-receive-pack HTTP/1.1" c.a.s.i.h.r.PreReceiveRepositoryHookAdapter Receive Hook com.isroot.stash.plugin.YaccHook failed.
com.atlassian.bitbucket.commit.NoSuchCommitException: Commit 'ac1480a9bdaa95b643268f857e90784e4b7acf84' does not exist in repository 'Test Repository 1'.
	at com.atlassian.bitbucket.scm.git.command.GitCommandExitHandler.newNoSuchCommitException(GitCommandExitHandler.java:167) ~[na:na]
	at com.atlassian.bitbucket.scm.git.command.GitCommandExitHandler.evaluateStdErr(GitCommandExitHandler.java:70) ~[na:na]
	at com.atlassian.bitbucket.scm.git.command.GitCommandExitHandler.onError(GitCommandExitHandler.java:197) ~[na:na]
	at com.atlassian.bitbucket.scm.DefaultCommandExitHandler.onExit(DefaultCommandExitHandler.java:31) ~[bitbucket-spi-4.10.2.jar:na]
	at com.atlassian.bitbucket.scm.BaseCommand.callExitHandler(BaseCommand.java:146) ~[bitbucket-spi-4.10.2.jar:na]
	at com.atlassian.bitbucket.scm.BaseCommand$CommandFuture.internalGet(BaseCommand.java:280) ~[bitbucket-spi-4.10.2.jar:na]
	at com.atlassian.bitbucket.scm.BaseCommand$CommandFuture.get(BaseCommand.java:244) ~[bitbucket-spi-4.10.2.jar:na]
	at com.atlassian.bitbucket.scm.BaseCommand.call(BaseCommand.java:83) ~[bitbucket-spi-4.10.2.jar:na]
	at com.isroot.stash.plugin.commits.CommitsServiceImpl.getNewCommits(CommitsServiceImpl.java:71) ~[na:na]
	at com.isroot.stash.plugin.YaccServiceImpl.checkRefChange(YaccServiceImpl.java:57) ~[na:na]
	at com.isroot.stash.plugin.YaccHook.onReceive(YaccHook.java:70) ~[na:na]
	at com.atlassian.stash.internal.hook.repository.PreReceiveRepositoryHookAdapter$1.visit(PreReceiveRepositoryHookAdapter.java:38) [bitbucket-service-impl-4.10.2.jar:na]
	at com.atlassian.stash.internal.hook.repository.PreReceiveRepositoryHookAdapter$1.visit(PreReceiveRepositoryHookAdapter.java:33) [bitbucket-service-impl-4.10.2.jar:na]
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService$RepositoryHookPagedTransactionCallback.doInTransaction(DefaultRepositoryHookService.java:573) [bitbucket-service-impl-4.10.2.jar:na]
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService$RepositoryHookPagedTransactionCallback.doInTransaction(DefaultRepositoryHookService.java:549) [bitbucket-service-impl-4.10.2.jar:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) [spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.visitEnabledHooks(DefaultRepositoryHookService.java:279) [bitbucket-service-impl-4.10.2.jar:na]
	at com.atlassian.stash.internal.plugin.OsgiSafeProxyProvider$1.invoke(OsgiSafeProxyProvider.java:93) [bitbucket-platform-4.10.2.jar:na]
	at com.atlassian.stash.internal.hook.repository.PreReceiveRepositoryHookAdapter.onReceive(PreReceiveRepositoryHookAdapter.java:33) [bitbucket-service-impl-4.10.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultBuiltInHookHandlerFactory$1.handle(DefaultBuiltInHookHandlerFactory.java:45) [bitbucket-service-impl-4.10.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.doHandleRequest(DefaultHookService.java:342) [bitbucket-service-impl-4.10.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.handleRequest(DefaultHookService.java:328) [bitbucket-service-impl-4.10.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.handleRawRequest(DefaultHookService.java:236) [bitbucket-service-impl-4.10.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService$1$1.run(DefaultHookService.java:202) [bitbucket-service-impl-4.10.2.jar:na]
	at com.atlassian.stash.internal.concurrent.StateTransferringExecutor$StateTransferringRunnable.run(StateTransferringExecutor.java:70) [bitbucket-platform-4.10.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]`

**Comment by sford** [comment]
Is that the version of git you are using for BBS itself? If so, it is not compatible with BBS 4.10.2. You will need to use an older version of git or upgrade to a newer version of BBS. See [BSERV-9388](https://jira.atlassian.com/browse/BSERV-9388).

**Comment by ooooo84** [comment]
@sford Thank you for your help. It works after I downgrade Git version to 2.10.2.
