### ISSUE TITLE
YACC rejecting annotated tags

### ISSUE THREAD

**Issue by hvanleemputten** [sford/yet-another-commit-checker#168]
After upgrading our Bitbucket server to use the latest released version of YACC, our TeamCity failed to tag successful builds. The hook is configured to check "Require Matching Committer Email", "Require Matching Committer Name" and "Commit Message Regex". The TeamCity server uses a SSH key to perform the tagging. 

The only way I found the tagging to work was to disable the "Require Matching Committer Email" and "Require Matching Committer Name" check.

TC error doesn't say much, it only says the following:
> [2017-10-10 11:20:19,341]   INFO [al executor 781] - ers.vcs.git.GitLabelingSupport - Tag  TeamCity-Windows-build-0.0.99.4392(3531)=5fb3a5ed01100c6069c306436f05c2006068ba3b was pushed with status REJECTED_OTHER_REASON for  (D:\Teamcity_config\system\caches\git\git-29EAEA98.git, ssh://git@our-server.com:7999/project/repo.git#master) in 26625ms (prepare pack 110ms) 
[2017-10-10 11:20:19,419]   WARN [al executor 781] -      jetbrains.buildServer.VCS - Failed to set label 'TeamCity-Windows-build-0.0.99.4392(3531)' 
jetbrains.buildServer.vcs.VcsException: The remote 'TeamCity-Windows-build-0.0.99.4392(3531)' tag was not created, status: REJECTED_OTHER_REASON, message: pre-receive hook declined
	at jetbrains.buildServer.buildTriggers.vcs.git.GitLabelingSupport.push(GitLabelingSupport.java:144)
	at jetbrains.buildServer.buildTriggers.vcs.git.GitLabelingSupport.label(GitLabelingSupport.java:102)
	at jetbrains.vcs.api.services.impl.LabelingServiceProvider$1.label(LabelingServiceProvider.java:1)
	at jetbrains.buildServer.vcs.impl.VcsLabeler.doSetLabel(VcsLabeler.java:101)
	at jetbrains.buildServer.vcs.impl.VcsLabeler.access$400(VcsLabeler.java:18)
	at jetbrains.buildServer.vcs.impl.VcsLabeler$2$1.run(VcsLabeler.java:4)
	at jetbrains.buildServer.util.ExceptionUtil$1.run(ExceptionUtil.java:41)
	at jetbrains.buildServer.vcs.impl.VcsLabeler$2$2.run(VcsLabeler.java:3)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

In the end I was able to reproduce this without TC, using a ssh key
> git tag -a tag_test -m "test"

> git push origin tag_test
Counting objects: 1, done.
Writing objects: 100% (1/1), 172 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: Push rejected by YACC
remote:
remote:   (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)
remote:    / ._. \      / ._. \      / ._. \      / ._. \      / ._. \
remote:  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__
remote: (_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)
remote:    || E ||      || R ||      || R ||      || O ||      || R ||
remote:  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '.
remote: (.-./`-'\.-.)(.-./`-`\.-.)(.-./`-`\.-.)(.-./`-'\.-.)(.-./`-`\.-.)
remote:  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'
remote:
remote:
remote: Push rejected.
remote:
remote: refs/tags/tag_test: expected committer name 'Access Key User - ---- END SSH2 PUBLIC KEY ----' but found 'unknown'
remote:
remote:
To ssh://git@our-server.com:7999/project/repo.git
 ! [remote rejected] tag_test -> tag_test (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@our-server.com:7999/project/repo.git'

> git show tag_test
tag tag_test
Tagger: unknown <User@xxxxxx.com>
Date:   Tue Oct 10 12:02:42 2017 +0200
...

Is there any way to exclude the user? it seems that specifying a username to exclude does not work in this use case.

**Comment by c-klinger** [comment]
We had the same problem on our side using. Provided Fix seems to work well, @sford please feel free to pull it.

**Comment by tosts** [comment]
This is in 1.19. So the issue can be closed, right?

**Comment by hvanleemputten** [comment]
I didn't realize this was fixed and released, so yes it can be closed
