### ISSUE TITLE
NullPointerException when using non-capturing group in regex

### ISSUE THREAD

**Issue by GunoH** [sford/yet-another-commit-checker#230]
Hi there,

When I use `(?:([A-Z]+-\d+)|BZ #\d+).*` as _Commit Message Regex_ in YACC and try to push a commit with a commit message like _BZ #543211 - Make a bugzilla-tracked change_, YACC fails with a `NullPointerException`:

    remote: Repository hook com.isroot.stash.plugin.yacc:yaccHook failed
    remote: java.lang.NullPointerException

I think this might be due to the `?:` in my regex. It is there because I want to check whether a commit message contains either a Jira reference or a reference to a legacy Bugzilla system:
* For Jira, it should check if the issue actually exists (so there should be a capture group)
* For Bugzilla, no additional checks are needed (so there should be **no** capture group)

This should be possible using a non-capturing group (see e.g. https://stackoverflow.com/a/3513858), but it seems YACC doesn't like that. 
Is this something that could be fixed? Or is there a workaround for this issue?

Thanks,
Guno

**Comment by GunoH** [comment]
Came up with a workaround myself; using the _Exclude by Regex_ field I can exclude the Bugzilla-commits from the Jira checks. That seems to work. I don't need the `?:` in my regex then.

**Comment by sford** [comment]
> Came up with a workaround myself
> (I'll try to get a hold of the full stacktrace)

Glad you figured out a workaround. I would still be curious to see a full stacktrace if possible.

**Comment by GunoH** [comment]
Got the stacktrace.
```
c.a.s.i.h.r.DefaultRepositoryHookService [AF/axon-framework[946]] Error calling com.atlassian.stash.internal.plugin.legacy.CompositeRepositoryHook.preUpdate (com.isroot.stash.plugin.yacc:yaccHook)
java.lang.NullPointerException: null
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at com.isroot.stash.plugin.IssueKey.parseIssueKeys(IssueKey.java:64)
	at com.isroot.stash.plugin.YaccServiceImpl.extractJiraIssuesFromCommitMessage(YaccServiceImpl.java:207)
	at com.isroot.stash.plugin.YaccServiceImpl.checkJiraIssues(YaccServiceImpl.java:226)
	at com.isroot.stash.plugin.YaccServiceImpl.checkCommit(YaccServiceImpl.java:96)
	at com.isroot.stash.plugin.YaccServiceImpl.checkRefChange(YaccServiceImpl.java:61)
	at com.isroot.stash.plugin.YaccHook.onReceive(YaccHook.java:70)
	at com.atlassian.stash.internal.plugin.legacy.PreReceiveRepositoryHookAdapter.preUpdate(PreReceiveRepositoryHookAdapter.java:29)
	at com.atlassian.stash.internal.plugin.legacy.CompositeRepositoryHook.lambda$preUpdate$2(CompositeRepositoryHook.java:70)
	at com.atlassian.stash.internal.plugin.legacy.CompositeRepositoryHook.handlingExceptions(CompositeRepositoryHook.java:86)
	at com.atlassian.stash.internal.plugin.legacy.CompositeRepositoryHook.preUpdate(CompositeRepositoryHook.java:69)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.preUpdate(DefaultRepositoryHookService.java:583)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.preUpdate(DefaultRepositoryHookService.java:284)
	at com.atlassian.stash.internal.hook.DefaultBuiltInHookHandlerFactory.lambda$preReceive$0(DefaultBuiltInHookHandlerFactory.java:33)
	at com.atlassian.stash.internal.scm.git.GitQuarantineHelper.lambda$null$0(GitQuarantineHelper.java:87)
	at com.atlassian.stash.internal.hook.DefaultHookService.doHandleRequest(DefaultHookService.java:303)
	at com.atlassian.stash.internal.hook.DefaultHookService.handleRequest(DefaultHookService.java:289)
	at com.atlassian.stash.internal.hook.DefaultHookService.handleRawRequest(DefaultHookService.java:230)
	at com.atlassian.stash.internal.hook.DefaultHookService$1.lambda$run$0(DefaultHookService.java:197)
	at com.atlassian.stash.internal.concurrent.DefaultTransferableStateManager$StateTransferringRunnable.run(DefaultTransferableStateManager.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.lang.Thread.run(Thread.java:745)
	... 26 frames trimmed
```

```
$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```
