### ISSUE TITLE
pushes failing when "Require Valid JIRA Issue(s)" is enabled in YACC

### ISSUE THREAD

**Issue by bharathnatarajan1** [sford/yet-another-commit-checker#231]
My pushes to bitbucket are failing when "Require Valid JIRA Issue(s)" is enabled in YACC for my repo.

BitBucket Version: Atlassian Bitbucket v5.15.2
Git Version: 2.9.5
YACC Version: 1.24

Error Details:
2019-12-03 11:29:58,214 WARN  [io-pump:thread-4] user1 @1BLLUPx689x33536x0 2h4uwi 11.160.28.2 SSH - git-receive-pack '/ep/myrepo.git'
org.slf4j.Logger com.isroot.stash.plugin.yacc:yaccHook:onCommitAdded failed: null
2019-12-03 11:29:58,217 WARN  [hook-callback:thread-2]  c.a.s.i.hook.DefaultHookService Hook socket I/O failed before the repository/hook could be identified
com.atlassian.bitbucket.ServerException: An error occurred while executing an external process: detailMessage
        at com.atlassian.bitbucket.scm.git.command.GitCommandExitHandler.evaluateThrowable(GitCommandExitHandler.java:120)
        at com.atlassian.bitbucket.scm.git.command.GitCommandExitHandler.onError(GitCommandExitHandler.java:208)
        at com.atlassian.stash.internal.scm.git.command.revlist.RevCoreExitHandler.onError(RevCoreExitHandler.java:52)
        at com.atlassian.bitbucket.scm.DefaultCommandExitHandler.onExit(DefaultCommandExitHandler.java:32)
        at com.atlassian.bitbucket.scm.BaseCommand.callExitHandler(BaseCommand.java:153)
        at com.atlassian.bitbucket.scm.BaseCommand$CommandFuture.internalGet(BaseCommand.java:287)
        at com.atlassian.bitbucket.scm.BaseCommand$CommandFuture.get(BaseCommand.java:251)
        at com.atlassian.bitbucket.scm.BaseCommand.call(BaseCommand.java:87)
        at com.atlassian.stash.internal.hook.repository.CachingRepositoryHookScmHelper.internalCommits(CachingRepositoryHookScmHelper.java:125)
        at com.atlassian.stash.internal.hook.repository.CachingRepositoryHookScmHelper$HookRequestCache.commits(CachingRepositoryHookScmHelper.java:354)
        at com.atlassian.stash.internal.hook.repository.CachingRepositoryHookScmHelper.commits(CachingRepositoryHookScmHelper.java:72)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookCallbackInvoker.streamIntroducedCommits(DefaultRepositoryHookCallbackInvoker.java:269)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookCallbackInvoker.streamCommitDetailsForRefChanges(DefaultRepositoryHookCallbackInvoker.java:203)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookCallbackInvoker.streamCommitDetails(DefaultRepositoryHookCallbackInvoker.java:131)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookCallbackInvoker.invokePreCallbacks(DefaultRepositoryHookCallbackInvoker.java:83)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.lambda$preUpdate$4(DefaultRepositoryHookService.java:485)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.preUpdate(DefaultRepositoryHookService.java:446)
        at com.atlassian.stash.internal.hook.DefaultBuiltInHookHandlerFactory.lambda$preReceive$0(DefaultBuiltInHookHandlerFactory.java:36)
        at com.atlassian.stash.internal.hook.DefaultHookService.doHandleRequest(DefaultHookService.java:301)
        at com.atlassian.stash.internal.hook.DefaultHookService.handleRequest(DefaultHookService.java:287)
        at com.atlassian.stash.internal.hook.DefaultHookService.handleRawRequest(DefaultHookService.java:221)
        at com.atlassian.stash.internal.hook.DefaultHookService$1.lambda$run$0(DefaultHookService.java:188)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.lang.Thread.run(Thread.java:748)
        ... 26 frames trimmed
Caused by: java.lang.NullPointerException: detailMessage
        at java.util.Objects.requireNonNull(Objects.java:228)
        at com.atlassian.bitbucket.hook.repository.SimpleRepositoryHookVeto.<init>(SimpleRepositoryHookVeto.java:21)
        at com.atlassian.bitbucket.hook.repository.RepositoryHookResult$Builder.veto(RepositoryHookResult.java:141)
        at com.atlassian.bitbucket.hook.repository.RepositoryHookResult.rejected(RepositoryHookResult.java:49)
        at com.atlassian.stash.internal.hook.repository.SafeRepositoryHookCommitCallbac

**Comment by bharathnatarajan1** [comment]
This issue was due to missing git library, once it was addressed in our bitbucket environment, the issue was resolved.
