### ISSUE TITLE
use stashs proxy support (JAVA_OPTS)

### ISSUE THREAD

**Issue by snoopotic** [sford/yet-another-commit-checker#54]
Hi.
It seems YACC does not make use of proxy settings if you have set them in stash via JAVA_OPTS (in setenv.sh)
To use several things (updater) and establish the Application link we've set a proxy but YACC seems to ignore it (Exception taken from atlassian-stash.log):

```
2015-06-01 16:04:47,605 ERROR [ajp-nio-127.0.0.1-8019-exec-280] <user1> @OVBLKLx964x2440493x2 g6di7r 192.168.xxx.xx "PUT /rest/api/latest/projects/PROJECTX/repos/projectx-legacy/settings/hooks/com.isroot.stash.plugin.yacc:yaccHook/settings HTTP/1.1" c.i.stash.plugin.ConfigValidator unexpected exception while trying to validate jql query
com.atlassian.sal.api.net.ResponseException: java.net.SocketTimeoutException: Read timed out
        at com.atlassian.sal.core.net.HttpClientRequest.executeAndReturn(HttpClientRequest.java:386) ~[sal-core-2.13.3.jar:na]
        at com.atlassian.applinks.core.auth.ApplicationLinkRequestAdaptor.executeAndReturn(ApplicationLinkRequestAdaptor.java:78) ~[na:na]
        at com.atlassian.applinks.core.auth.oauth.OAuthRequest.executeAndReturn(OAuthRequest.java:76) ~[na:na]
        at com.atlassian.applinks.core.auth.AbstractApplicationLinkRequest.execute(AbstractApplicationLinkRequest.java:159) ~[na:na]
        at com.isroot.stash.plugin.JiraServiceImpl.executeJqlQuery(JiraServiceImpl.java:147) ~[na:na]
        at com.isroot.stash.plugin.JiraServiceImpl.isJqlQueryValid(JiraServiceImpl.java:120) ~[na:na]
        at com.isroot.stash.plugin.ConfigValidator.validate(ConfigValidator.java:47) ~[na:na]
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.validateSettings(DefaultRepositoryHookService.java:506) [stash-service-impl-3.6.1.jar:na]
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.setSettings(DefaultRepositoryHookService.java:269) [stash-service-impl-3.6.1.jar:na]
        at com.atlassian.stash.internal.rest.repository.RepositoryHookResource.setSettings(RepositoryHookResource.java:299) [stash-rest-3.6.1.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) [applinks-plugin-4.3.5_1418190064000.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:86) [StashAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:111) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:77) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:100) [atlassian-trusted-apps-core-3.0.8.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) [atlassian-oauth-service-provider-plugin-1.9.9_1418190064000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:32) [analytics-client-3.53_1418190066000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-3.53_1418190066000.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:89) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) [stash-service-impl-3.6.1.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
        ... 253 frames trimmed
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_31]
        at java.net.SocketInputStream.read(SocketInputStream.java:150) ~[na:1.8.0_31]
        at java.net.SocketInputStream.read(SocketInputStream.java:121) ~[na:1.8.0_31]
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_31]
        at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_31]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:961) ~[na:1.8.0_31]
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:918) ~[na:1.8.0_31]
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_31]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_31]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[na:1.8.0_31]
        at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) ~[commons-httpclient-3.1.jar:na]
        at com.atlassian.sal.core.net.HttpClientRequest.executeMethod(HttpClientRequest.java:600) ~[sal-core-2.13.3.jar:na]
        at com.atlassian.sal.core.net.HttpClientRequest.executeMethod(HttpClientRequest.java:556) ~[sal-core-2.13.3.jar:na]
        at com.atlassian.sal.core.net.HttpClientRequest.executeAndReturn(HttpClientRequest.java:360) ~[sal-core-2.13.3.jar:na]
        ... 24 common frames omitted
```

The Read Timeout indicates it has a connection error. 

We tested on an environment that does not use any proxy to Jira that worked. So we are pretty sure we need proxy support for YACC. :)

**Comment by sford** [comment]
Hey @snoopotic ,

What system properties are you using to configure a proxy in `JAVA_OPTS`?

Trying to understand what would be involved to fix this... as it stands now, YACC uses existing application links so it isn't doing much other than asking Stash to make a request to JIRA. I did find https://jira.atlassian.com/browse/STASH-7339... looks like there might be a Stash bug related to application links and proxies? Is that what you are running into?

**Comment by snoopotic** [comment]
Hi, thanks for the reply.
Well, the issue you posted I cannot confirm. It seems the reporter means something else... !?

I use following setting (in setenv.sh about line 274 below the first "JAVA_OPTS"):
    # PROXY
    JAVA_OPTS="$JAVA_OPTS -Dhttp.proxyHost=proxy.example.com -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts=\"ourgit.example.com|*.internal.hosts|localhost|127.0.0.1\""
    JAVA_OPTS="$JAVA_OPTS -Dhttps.proxyHost=proxy.example.com -Dhttps.proxyPort=3128 -Dhttps.nonProxyHosts=\"ourgit.example.com|*.internal.hosts|localhost|127.0.0.1\""

- Marketplace Works (using proxy)
- Application Link works (OAUTH) --> Jira Integration i.O.

Only described YACC Scenario using JQL does not work. Everythng else of YACC works well.
