### ISSUE TITLE
NullPointerException is global yacc settings have not been configured yet

### ISSUE THREAD

**Issue by sford** [sford/yet-another-commit-checker#74]
```
[INFO] [talledLocalContainer] 2015-09-14 22:10:36,461 WARN  [threadpool:thread-4] admin @BYMT0Qx1330x166x0 192.168.50.1 "POST /scm/project_1/rep_1.git/git-receive-pack HTTP/1.1" c.a.s.i.h.DefaultBuiltInHookHandlerFactory PreReceiveHook failed, push will be rejected.
[INFO] [talledLocalContainer] java.lang.NullPointerException: null
[INFO] [talledLocalContainer]   at com.isroot.stash.plugin.YaccPreReceiveHook.buildYaccConfig(YaccPreReceiveHook.java:84) ~[na:na]
[INFO] [talledLocalContainer]   at com.isroot.stash.plugin.YaccPreReceiveHook.onReceive(YaccPreReceiveHook.java:72) ~[na:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.hook.DefaultBuiltInHookHandlerFactory$1.handle(DefaultBuiltInHookHandlerFactory.java:43) ~[stash-service-impl-3.5.1.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.hook.DefaultHookService.doHandleRequest(DefaultHookService.java:353) [stash-service-impl-3.5.1.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.hook.DefaultHookService.handleRequest(DefaultHookService.java:339) [stash-service-impl-3.5.1.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.hook.DefaultHookService.handleRawRequest(DefaultHookService.java:250) [stash-service-impl-3.5.1.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.hook.DefaultHookService$2$1.run(DefaultHookService.java:210) [stash-service-impl-3.5.1.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.concurrent.StateTransferringExecutor$StateTransferringRunnable.run(StateTransferringExecutor.java:69) [stash-platform-3.5.1.jar:na]
[INFO] [talledLocalContainer]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_67]
[INFO] [talledLocalContainer]   at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_67]
[INFO] [talledLocalContainer]   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_67]
[INFO] [talledLocalContainer]   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_67]
[INFO] [talledLocalContainer]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
[INFO] [talledLocalContainer]   at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
[INFO] [talledLocalContainer]   ... 1 frame trimmed
```

Repo Steps:

1. `atlas-run`
2. Clone `rep_1`
3. Try pushing a commit

**Comment by sford** [comment]
This can be worked around by going to the global config and simply saving the form.
