### ISSUE TITLE
Initial pushes failing when YACC isn't enabled on the repo

### ISSUE THREAD

**Issue by kellyschoenhofen** [sford/yet-another-commit-checker#92]
So we're seeing an issue where large repos with alot of commits (25k-300k) are failing on a pre-receive hook exception with YACC classes in the trace, but YACC is disabled for the repo. 
After looking at issue #72 and #74 I went to the global settings, which were completely blank, and clicked "Save" at the bottom. Same issue on a re-push. I checked one setting and clicked Save again, same issue on a re-push. I globally disabled YACC from the manage plugins page and then the new repo/initial pushes worked. What we see is the data transfer succeeds and then Bitbucket pauses (from the git client point of view) and it's obviously chewing through all the commits. It's a bug to me because YACC is not enabled for that repo. Why is YACC looking at the commits? After disabling YACC globally, the very long (up to 30 minute) pause after the transfer is complete before it would fail with an exception completely went away. 

We're on Bitbucket Server 4.0.2, YACC 1.10. 

Here's part of our bitbucket log:

```
2015-11-15 12:05:05,036 WARN  [threadpool:thread-5] jviguera @1MRP1UDx392x1091177x0 dcgrwk 127.0.0.1 SSH - git-receive-pack '/dea-new/platform_frameworks_native.git' c.a.s.i.h.DefaultBuiltInHookHandlerFactory PreReceiveHook failed, push will be rejected.
java.util.NoSuchElementException: null
	at com.google.common.collect.Iterators$1.next(Iterators.java:80) ~[guava-18.0.jar:na]
	at com.atlassian.bitbucket.util.PagedIterable$PagedIterator.next(PagedIterable.java:48) ~[bitbucket-util-4.0.2.jar:na]
	at com.isroot.stash.plugin.CommitsServiceImpl.getNewCommits(CommitsServiceImpl.java:97) ~[na:na]
	at com.isroot.stash.plugin.YaccServiceImpl.checkRefChange(YaccServiceImpl.java:53) ~[na:na]
	at com.isroot.stash.plugin.YaccHook.onReceive(YaccHook.java:70) ~[na:na]
	at com.isroot.stash.plugin.YaccPreReceiveHook.onReceive(YaccPreReceiveHook.java:67) ~[na:na]
	at com.atlassian.stash.internal.hook.DefaultBuiltInHookHandlerFactory$1.handle(DefaultBuiltInHookHandlerFactory.java:45) ~[bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.doHandleRequest(DefaultHookService.java:343) [bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.handleRequest(DefaultHookService.java:329) [bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.handleRawRequest(DefaultHookService.java:237) [bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService$1$1.run(DefaultHookService.java:203) [bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.concurrent.StateTransferringExecutor$StateTransferringRunnable.run(StateTransferringExecutor.java:73) [bitbucket-platform-4.0.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
	... 1 frame trimmed
2015-11-15 12:05:05,037 WARN  [threadpool:thread-7] jviguera @1MRP1UDx331x1085087x0 1sfp735 127.0.0.1 SSH - git-receive-pack '/dea-new/platform_frameworks_base.git' c.a.s.i.h.DefaultBuiltInHookHandlerFactory PreReceiveHook failed, push will be rejected.
java.util.NoSuchElementException: null
	at com.google.common.collect.Iterators$1.next(Iterators.java:80) ~[guava-18.0.jar:na]
	at com.atlassian.bitbucket.util.PagedIterable$PagedIterator.next(PagedIterable.java:48) ~[bitbucket-util-4.0.2.jar:na]
	at com.isroot.stash.plugin.CommitsServiceImpl.getNewCommits(CommitsServiceImpl.java:97) ~[na:na]
	at com.isroot.stash.plugin.YaccServiceImpl.checkRefChange(YaccServiceImpl.java:53) ~[na:na]
	at com.isroot.stash.plugin.YaccHook.onReceive(YaccHook.java:70) ~[na:na]
	at com.isroot.stash.plugin.YaccPreReceiveHook.onReceive(YaccPreReceiveHook.java:67) ~[na:na]
	at com.atlassian.stash.internal.hook.DefaultBuiltInHookHandlerFactory$1.handle(DefaultBuiltInHookHandlerFactory.java:45) ~[bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.doHandleRequest(DefaultHookService.java:343) [bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.handleRequest(DefaultHookService.java:329) [bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.handleRawRequest(DefaultHookService.java:237) [bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService$1$1.run(DefaultHookService.java:203) [bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.concurrent.StateTransferringExecutor$StateTransferringRunnable.run(StateTransferringExecutor.java:73) [bitbucket-platform-4.0.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
	... 1 frame trimmed
2015-11-15 12:05:05,039 ERROR [threadpool:thread-7]  c.a.s.i.hook.DefaultHookService An exception occurred communicating with 'git-pre-receive' hook in repository 2938
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_60]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[na:1.8.0_60]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132) ~[na:1.8.0_60]
	at java.io.DataOutputStream.write(DataOutputStream.java:88) ~[na:1.8.0_60]
	at com.atlassian.stash.internal.hook.SocketTransferOutput.writeUnsignedShort(SocketTransferOutput.java:90) ~[bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.hook.SocketTransferOutput.writeExitCode(SocketTransferOutput.java:50) ~[bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.writeResponse(DefaultHookService.java:321) ~[bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService.handleRawRequest(DefaultHookService.java:247) ~[bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.hook.DefaultHookService$1$1.run(DefaultHookService.java:203) [bitbucket-service-impl-4.0.2.jar:na]
	at com.atlassian.stash.internal.concurrent.StateTransferringExecutor$StateTransferringRunnable.run(StateTransferringExecutor.java:73) [bitbucket-platform-4.0.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_60]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
	... 1 frame trimmed
2015-11-15 12:05:07,234 INFO  [localhost-startStop-2]  c.a.s.internal.home.HomeLockAcquirer Releasing lock on /var/atlassian/application-data/bitbucket/shared
2015-11-15 12:05:07,266 INFO  [localhost-startStop-2]  c.a.s.internal.home.HomeLockAcquirer Releasing lock on /var/atlassian/application-data/bitbucket
2015-11-15 12:05:07,272 INFO  [localhost-startStop-2]  c.a.s.i.server.BuildInfoLogger Bitbucket 4.0.2 has shut down
```

**Comment by itay** [comment]
We're suffering from a similar issue - it's clear that YACC is still running against our repo even when I disable the per-repo configuration. It takes me disabling the entire plugin globally to get it to work.

This is a problem because on some repos with large numbers of commits and branches, it causes quite a bit of slowdown, and there is currently no way for me to disable it for some repos.

The issue seems to be here:

```
        if (hook.isEnabled() && hook.isConfigured()) {
            // Repository hook is configured and enabled.
            // Repository hook overrides default pre-receive hook configuration
            log.debug("PreReceiveRepositoryHook configured. Skip PreReceiveHook");
            return true;
        } else {
            // Repository hook not configured
            log.debug("PreReceiveRepositoryHook not configured. Run PreReceiveHook");

            Settings storedConfig = YaccUtils.buildYaccConfig(pluginSettingsFactory, repositoryHookService);

            return yaccHook.onReceive(new RepositoryHookContext(repository, storedConfig), refChanges, hookResponse);
        }
```

As far as I can tell, you have two conditions: 
1. If the hook is enabled on the current repo specifically, just keep moving on.
2. If the hook is not enabled on the current repo, then run the global configuration.

The problem is that calling ```yaccHook.onReceive``` ends up iterating over all the ref changes (https://github.com/sford/yet-another-commit-checker/blob/master/src/main/java/com/isroot/stash/plugin/YaccHook.java#L38), which in turn means it's trying to calculate the changesets and run the conditions against them. This happens *even if not conditions are enabled*.

The fix seems relatively simple - if no conditions are enabled, `onReceive` should be a no-op.

**Comment by sford** [comment]
@itay , thanks for triaging and the suggested fix! I totally see the issue. I implemented the fix in fbd880b8. I don't have easy access to a large enough repository to expose the original problem... would you or @kellyschoenhofen be able to try out fbd880b8 to see how it works?

**Comment by itay** [comment]
@sford change looks good - I can't try it out unfortunately on our production instance as we are under a year-end moratorium. 

You should be able to test it out pretty easily though - just create a repo for which YACC is not enabled, and don't have any global settings turned on. Without the fix - you'll still run through each change, but with the fix, you should not run through any of them.

**Comment by itay** [comment]
@sford any chance of pushing out the release?

**Comment by sford** [comment]
@itay yeah, I will push out a release when I get home today :+1:

**Comment by sford** [comment]
1.11 has been released :+1:

**Comment by marlang** [comment]
Will you be fixing this on the 1.8 branch of your code? (pre Bitbucket 4.0)

**Comment by itay** [comment]
@sford I have some bad news :( I updated to 1.11 finally - it does solve the perf problem, but it seems that now it no longer enforces the committer email check. I tried enabling/disabling the plugin on that specific repo, saving it without the requirement and then adding it back, etc, but nothing seems to take - it just lets the commit through.

**Comment by sford** [comment]
@marlang Wasn't planning on it... Do you use the global settings? If not, you could potentially downgrade to 1.6 if you need an immediate fix.

@itay I am assuming that you have all global settings disabled? Trying to understand how fbd880b  might have affected other settings. Do you happen to have any of the exclude settings turned on? Like exclude service users? This could potentially affect users who are using service user SSH keys.

**Comment by itay** [comment]
Both are true. I have no global settings and I have it set to exclude service users - though this was not a problem prior to the upgrade, as far as I know.

**Comment by marlang** [comment]
Hi Sean,

Thanks for the quick response.  To downgrade, do you know if we lose previous settings?  I can't just upload 1.6 to downgrade, I will need to uninstall it and re-install and I'm not sure what that will do to previously entered settings.

Thanks,

[tomorrow_anthem_H.png]


Mark Lang
Software Engineer
GIS Engineering IT
marlang@cisco.com<mailto:marlang@cisco.com>
Phone: 919.392.4139
Mobile: 919.280.0672


7025-6 Kit Creek Road PO Box14987           Research Triangle Park                               NORTH CAROLINA 27709-4987               United States





[green.gif] Think before you print.

This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message.


For corporate legal information go to:
http://www.cisco.com/web/about/doing_business/legal/cri/index.html

**Comment by sford** [comment]
@itay I just spot checked YACC 1.11 was able to get YACC to block a commit with a wrong committer email. Would you be able to turn on [debugging logging for YACC](https://github.com/sford/yet-another-commit-checker#enable-logging) and try to reproduce the issue? That should give us some additional logging to give us a better idea what might be happening.

Thanks!

**Comment by itay** [comment]
Nevermind I'm just dumb. For some reason I was testing with GIT_AUTHOR_EMAIL, but should have tested with GIT_COMMITTER_EMAIL - that one worked fine.

**Comment by sford** [comment]
@itay  great, glad everything is working, including the performance tweaks!
